spring:
  datasource:

    url: jdbc:mysql://localhost:3307/rest_with_spring_boot_erudio
    username: root
    password: admin123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true